parameters:
#    httpi_mycv_core.example.class: Httpi\Mycv\Bundle\CoreBundle\Example

services:
#    httpi_mycv_core.example:
#        class: %httpi_mycv_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
