parameters:
#    httpi_mycv_demo.example.class: Httpi\Mycv\Bundle\DemoBundle\Example

services:
#    httpi_mycv_demo.example:
#        class: %httpi_mycv_demo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
